/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData date = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downloaded = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_type = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_menu = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rename = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData size_box = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compressed = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData executable = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData programming = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_i = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
